spring.application.name=inventario-api

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/db_inventario_promart}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:promart2024}
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JWT
app.jwt.secret=promart2024InventarioSecretKeyPromartPeruJWT_HS256
app.jwt.expiration=28800000

